// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knojnkfrymnmqwatsyvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtub2pua2ZyeW1ubXF3YXRzeXZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5Njg3MjcsImV4cCI6MjA1OTU0NDcyN30.fCjg4UX8sLORSkmI1pdwf0-pcwJ-2jbSr1r0n-Hxlp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);